---
name: grd2shp_xagg_2
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.10
  - pip
  # Production dependencies defined here (as well as in requirements.txt)
  - click
  - pandas
  - geopandas
  - rasterstats
  - xarray
  - dask
  - bottleneck
  - numpy
  - metpy
  - netcdf4
  - jupyterlab
  - hvplot
  - xesmf>= 0.5.2
  - pip:
      - "git+https://github.com/rmcd-mscb/xagg.git@nc_prep_fix"
