package:
  name: grd2shp_xagg
  version: 0.0.1-dev0

source:
  path: src

build:
  number: 0
  script: "/usr/bin/env python -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports: []  # <-- remove the brackets if actually importing here.
    # - some_package
  requires:
    - pytest
  commands:
    - pytest tests/

about:
  home: https://github.com/rmcd-mscb/grd2shp_xagg
  license: MIT
  license_file: LICENSE.rst
  summary: 'Interpolate gridded input to geometry polygons'
  # The remaining entries in this section are optional, but recommended.
  description: 'This package serves as an interface to the xagg package for interpolating climate fording datasets to hydrologic model fabrics.'
  doc_url: https://grd2shp_xagg.readthedocs.io/
  dev_url: https://github.com/rmcd-mscb/grd2shp_xagg

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - rmcd-mscb
  development-status:
    - Development Status :: 1 - Planning
